services:
  postgres:
    image: postgres:16-alpine
    container_name: etl_data_quality_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: etl_data_quality
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d etl_data_quality"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
